#include <threadsafe/threadsafe.h>
using threadsafe::is_sendable_v;
struct Deep0 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep0>);
struct Deep1 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep1>);
struct Deep2 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep2>);
struct Deep3 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep3>);
struct Deep4 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep4>);
struct Deep5 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep5>);
struct Deep6 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep6>);
struct Deep7 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep7>);
struct Deep8 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep8>);
struct Deep9 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep9>);
struct Deep10 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep10>);
struct Deep11 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep11>);
struct Deep12 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep12>);
struct Deep13 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep13>);
struct Deep14 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep14>);
struct Deep15 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep15>);
struct Deep16 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep16>);
struct Deep17 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep17>);
struct Deep18 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep18>);
struct Deep19 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep19>);
struct Deep20 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep20>);
struct Deep21 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep21>);
struct Deep22 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep22>);
struct Deep23 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep23>);
struct Deep24 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep24>);
struct Deep25 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep25>);
struct Deep26 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep26>);
struct Deep27 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep27>);
struct Deep28 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep28>);
struct Deep29 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep29>);
struct Deep30 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep30>);
struct Deep31 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep31>);
struct Deep32 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep32>);
struct Deep33 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep33>);
struct Deep34 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep34>);
struct Deep35 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep35>);
struct Deep36 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep36>);
struct Deep37 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep37>);
struct Deep38 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep38>);
struct Deep39 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep39>);
struct Deep40 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep40>);
struct Deep41 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep41>);
struct Deep42 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep42>);
struct Deep43 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep43>);
struct Deep44 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep44>);
struct Deep45 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep45>);
struct Deep46 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep46>);
struct Deep47 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep47>);
struct Deep48 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep48>);
struct Deep49 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep49>);
struct Deep50 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep50>);
struct Deep51 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep51>);
struct Deep52 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep52>);
struct Deep53 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep53>);
struct Deep54 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep54>);
struct Deep55 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep55>);
struct Deep56 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep56>);
struct Deep57 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep57>);
struct Deep58 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep58>);
struct Deep59 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep59>);
struct Deep60 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep60>);
struct Deep61 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep61>);
struct Deep62 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep62>);
struct Deep63 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep63>);
struct Deep64 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep64>);
struct Deep65 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep65>);
struct Deep66 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep66>);
struct Deep67 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep67>);
struct Deep68 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep68>);
struct Deep69 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep69>);
struct Deep70 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep70>);
struct Deep71 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep71>);
struct Deep72 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep72>);
struct Deep73 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep73>);
struct Deep74 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep74>);
struct Deep75 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep75>);
struct Deep76 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep76>);
struct Deep77 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep77>);
struct Deep78 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep78>);
struct Deep79 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep79>);
struct Deep80 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep80>);
struct Deep81 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep81>);
struct Deep82 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep82>);
struct Deep83 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep83>);
struct Deep84 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep84>);
struct Deep85 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep85>);
struct Deep86 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep86>);
struct Deep87 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep87>);
struct Deep88 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep88>);
struct Deep89 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep89>);
struct Deep90 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep90>);
struct Deep91 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep91>);
struct Deep92 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep92>);
struct Deep93 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep93>);
struct Deep94 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep94>);
struct Deep95 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep95>);
struct Deep96 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep96>);
struct Deep97 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep97>);
struct Deep98 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep98>);
struct Deep99 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep99>);
struct Deep100 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep100>);
struct Deep101 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep101>);
struct Deep102 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep102>);
struct Deep103 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep103>);
struct Deep104 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep104>);
struct Deep105 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep105>);
struct Deep106 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep106>);
struct Deep107 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep107>);
struct Deep108 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep108>);
struct Deep109 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep109>);
struct Deep110 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep110>);
struct Deep111 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep111>);
struct Deep112 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep112>);
struct Deep113 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep113>);
struct Deep114 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep114>);
struct Deep115 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep115>);
struct Deep116 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep116>);
struct Deep117 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep117>);
struct Deep118 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep118>);
struct Deep119 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep119>);
struct Deep120 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep120>);
struct Deep121 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep121>);
struct Deep122 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep122>);
struct Deep123 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep123>);
struct Deep124 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep124>);
struct Deep125 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep125>);
struct Deep126 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep126>);
struct Deep127 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep127>);
struct Deep128 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep128>);
struct Deep129 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep129>);
struct Deep130 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep130>);
struct Deep131 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep131>);
struct Deep132 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep132>);
struct Deep133 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep133>);
struct Deep134 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep134>);
struct Deep135 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep135>);
struct Deep136 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep136>);
struct Deep137 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep137>);
struct Deep138 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep138>);
struct Deep139 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep139>);
struct Deep140 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep140>);
struct Deep141 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep141>);
struct Deep142 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep142>);
struct Deep143 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep143>);
struct Deep144 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep144>);
struct Deep145 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep145>);
struct Deep146 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep146>);
struct Deep147 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep147>);
struct Deep148 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep148>);
struct Deep149 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep149>);
struct Deep150 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep150>);
struct Deep151 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep151>);
struct Deep152 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep152>);
struct Deep153 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep153>);
struct Deep154 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep154>);
struct Deep155 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep155>);
struct Deep156 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep156>);
struct Deep157 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep157>);
struct Deep158 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep158>);
struct Deep159 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep159>);
struct Deep160 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep160>);
struct Deep161 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep161>);
struct Deep162 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep162>);
struct Deep163 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep163>);
struct Deep164 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep164>);
struct Deep165 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep165>);
struct Deep166 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep166>);
struct Deep167 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep167>);
struct Deep168 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep168>);
struct Deep169 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep169>);
struct Deep170 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep170>);
struct Deep171 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep171>);
struct Deep172 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep172>);
struct Deep173 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep173>);
struct Deep174 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep174>);
struct Deep175 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep175>);
struct Deep176 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep176>);
struct Deep177 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep177>);
struct Deep178 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep178>);
struct Deep179 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep179>);
struct Deep180 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep180>);
struct Deep181 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep181>);
struct Deep182 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep182>);
struct Deep183 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep183>);
struct Deep184 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep184>);
struct Deep185 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep185>);
struct Deep186 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep186>);
struct Deep187 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep187>);
struct Deep188 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep188>);
struct Deep189 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep189>);
struct Deep190 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep190>);
struct Deep191 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep191>);
struct Deep192 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep192>);
struct Deep193 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep193>);
struct Deep194 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep194>);
struct Deep195 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep195>);
struct Deep196 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep196>);
struct Deep197 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep197>);
struct Deep198 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep198>);
struct Deep199 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int *borrowed;
};
static_assert(!is_sendable_v<Deep199>);
