#include <threadsafe/threadsafe.h>
using namespace threadsafe;
struct Leaf { int value; };
struct Wide {
    Leaf member0;
    Leaf member1;
    Leaf member2;
    Leaf member3;
    Leaf member4;
    Leaf member5;
    Leaf member6;
    Leaf member7;
    Leaf member8;
    Leaf member9;
    Leaf member10;
    Leaf member11;
    Leaf member12;
    Leaf member13;
    Leaf member14;
    Leaf member15;
    Leaf member16;
    Leaf member17;
    Leaf member18;
    Leaf member19;
    Leaf member20;
    Leaf member21;
    Leaf member22;
    Leaf member23;
    Leaf member24;
    Leaf member25;
    Leaf member26;
    Leaf member27;
    Leaf member28;
    Leaf member29;
    Leaf member30;
    Leaf member31;
    Leaf member32;
    Leaf member33;
    Leaf member34;
    Leaf member35;
    Leaf member36;
    Leaf member37;
    Leaf member38;
    Leaf member39;
    Leaf member40;
    Leaf member41;
    Leaf member42;
    Leaf member43;
    Leaf member44;
    Leaf member45;
    Leaf member46;
    Leaf member47;
    Leaf member48;
    Leaf member49;
};
static_assert(is_sendable_v<Wide>);
int main(){}
