#include <threadsafe/threadsafe.h>
using namespace threadsafe;
struct Chain0_0 { int value; };
struct Chain0_1 { Chain0_0 inner; int extra; };
struct Chain0_2 { Chain0_1 inner; int extra; };
struct Chain0_3 { Chain0_2 inner; int extra; };
struct Chain0_4 { Chain0_3 inner; int extra; };
struct Chain0_5 { Chain0_4 inner; int extra; };
struct Chain0_6 { Chain0_5 inner; int extra; };
struct Chain0_7 { Chain0_6 inner; int extra; };
struct Chain0_8 { Chain0_7 inner; int extra; };
struct Chain0_9 { Chain0_8 inner; int extra; };
struct Chain0_10 { Chain0_9 inner; int extra; };
struct Chain0_11 { Chain0_10 inner; int extra; };
struct Chain0_12 { Chain0_11 inner; int extra; };
struct Chain0_13 { Chain0_12 inner; int extra; };
struct Chain0_14 { Chain0_13 inner; int extra; };
struct Chain0_15 { Chain0_14 inner; int extra; };
struct Chain0_16 { Chain0_15 inner; int extra; };
struct Chain0_17 { Chain0_16 inner; int extra; };
struct Chain0_18 { Chain0_17 inner; int extra; };
struct Chain0_19 { Chain0_18 inner; int extra; };
struct Chain0_20 { Chain0_19 inner; int extra; };
static_assert(is_sendable_v<Chain0_20>);
struct Chain1_0 { int value; };
struct Chain1_1 { Chain1_0 inner; int extra; };
struct Chain1_2 { Chain1_1 inner; int extra; };
struct Chain1_3 { Chain1_2 inner; int extra; };
struct Chain1_4 { Chain1_3 inner; int extra; };
struct Chain1_5 { Chain1_4 inner; int extra; };
struct Chain1_6 { Chain1_5 inner; int extra; };
struct Chain1_7 { Chain1_6 inner; int extra; };
struct Chain1_8 { Chain1_7 inner; int extra; };
struct Chain1_9 { Chain1_8 inner; int extra; };
struct Chain1_10 { Chain1_9 inner; int extra; };
struct Chain1_11 { Chain1_10 inner; int extra; };
struct Chain1_12 { Chain1_11 inner; int extra; };
struct Chain1_13 { Chain1_12 inner; int extra; };
struct Chain1_14 { Chain1_13 inner; int extra; };
struct Chain1_15 { Chain1_14 inner; int extra; };
struct Chain1_16 { Chain1_15 inner; int extra; };
struct Chain1_17 { Chain1_16 inner; int extra; };
struct Chain1_18 { Chain1_17 inner; int extra; };
struct Chain1_19 { Chain1_18 inner; int extra; };
struct Chain1_20 { Chain1_19 inner; int extra; };
static_assert(is_sendable_v<Chain1_20>);
struct Chain2_0 { int value; };
struct Chain2_1 { Chain2_0 inner; int extra; };
struct Chain2_2 { Chain2_1 inner; int extra; };
struct Chain2_3 { Chain2_2 inner; int extra; };
struct Chain2_4 { Chain2_3 inner; int extra; };
struct Chain2_5 { Chain2_4 inner; int extra; };
struct Chain2_6 { Chain2_5 inner; int extra; };
struct Chain2_7 { Chain2_6 inner; int extra; };
struct Chain2_8 { Chain2_7 inner; int extra; };
struct Chain2_9 { Chain2_8 inner; int extra; };
struct Chain2_10 { Chain2_9 inner; int extra; };
struct Chain2_11 { Chain2_10 inner; int extra; };
struct Chain2_12 { Chain2_11 inner; int extra; };
struct Chain2_13 { Chain2_12 inner; int extra; };
struct Chain2_14 { Chain2_13 inner; int extra; };
struct Chain2_15 { Chain2_14 inner; int extra; };
struct Chain2_16 { Chain2_15 inner; int extra; };
struct Chain2_17 { Chain2_16 inner; int extra; };
struct Chain2_18 { Chain2_17 inner; int extra; };
struct Chain2_19 { Chain2_18 inner; int extra; };
struct Chain2_20 { Chain2_19 inner; int extra; };
static_assert(is_sendable_v<Chain2_20>);
struct Chain3_0 { int value; };
struct Chain3_1 { Chain3_0 inner; int extra; };
struct Chain3_2 { Chain3_1 inner; int extra; };
struct Chain3_3 { Chain3_2 inner; int extra; };
struct Chain3_4 { Chain3_3 inner; int extra; };
struct Chain3_5 { Chain3_4 inner; int extra; };
struct Chain3_6 { Chain3_5 inner; int extra; };
struct Chain3_7 { Chain3_6 inner; int extra; };
struct Chain3_8 { Chain3_7 inner; int extra; };
struct Chain3_9 { Chain3_8 inner; int extra; };
struct Chain3_10 { Chain3_9 inner; int extra; };
struct Chain3_11 { Chain3_10 inner; int extra; };
struct Chain3_12 { Chain3_11 inner; int extra; };
struct Chain3_13 { Chain3_12 inner; int extra; };
struct Chain3_14 { Chain3_13 inner; int extra; };
struct Chain3_15 { Chain3_14 inner; int extra; };
struct Chain3_16 { Chain3_15 inner; int extra; };
struct Chain3_17 { Chain3_16 inner; int extra; };
struct Chain3_18 { Chain3_17 inner; int extra; };
struct Chain3_19 { Chain3_18 inner; int extra; };
struct Chain3_20 { Chain3_19 inner; int extra; };
static_assert(is_sendable_v<Chain3_20>);
struct Chain4_0 { int value; };
struct Chain4_1 { Chain4_0 inner; int extra; };
struct Chain4_2 { Chain4_1 inner; int extra; };
struct Chain4_3 { Chain4_2 inner; int extra; };
struct Chain4_4 { Chain4_3 inner; int extra; };
struct Chain4_5 { Chain4_4 inner; int extra; };
struct Chain4_6 { Chain4_5 inner; int extra; };
struct Chain4_7 { Chain4_6 inner; int extra; };
struct Chain4_8 { Chain4_7 inner; int extra; };
struct Chain4_9 { Chain4_8 inner; int extra; };
struct Chain4_10 { Chain4_9 inner; int extra; };
struct Chain4_11 { Chain4_10 inner; int extra; };
struct Chain4_12 { Chain4_11 inner; int extra; };
struct Chain4_13 { Chain4_12 inner; int extra; };
struct Chain4_14 { Chain4_13 inner; int extra; };
struct Chain4_15 { Chain4_14 inner; int extra; };
struct Chain4_16 { Chain4_15 inner; int extra; };
struct Chain4_17 { Chain4_16 inner; int extra; };
struct Chain4_18 { Chain4_17 inner; int extra; };
struct Chain4_19 { Chain4_18 inner; int extra; };
struct Chain4_20 { Chain4_19 inner; int extra; };
static_assert(is_sendable_v<Chain4_20>);
struct Chain5_0 { int value; };
struct Chain5_1 { Chain5_0 inner; int extra; };
struct Chain5_2 { Chain5_1 inner; int extra; };
struct Chain5_3 { Chain5_2 inner; int extra; };
struct Chain5_4 { Chain5_3 inner; int extra; };
struct Chain5_5 { Chain5_4 inner; int extra; };
struct Chain5_6 { Chain5_5 inner; int extra; };
struct Chain5_7 { Chain5_6 inner; int extra; };
struct Chain5_8 { Chain5_7 inner; int extra; };
struct Chain5_9 { Chain5_8 inner; int extra; };
struct Chain5_10 { Chain5_9 inner; int extra; };
struct Chain5_11 { Chain5_10 inner; int extra; };
struct Chain5_12 { Chain5_11 inner; int extra; };
struct Chain5_13 { Chain5_12 inner; int extra; };
struct Chain5_14 { Chain5_13 inner; int extra; };
struct Chain5_15 { Chain5_14 inner; int extra; };
struct Chain5_16 { Chain5_15 inner; int extra; };
struct Chain5_17 { Chain5_16 inner; int extra; };
struct Chain5_18 { Chain5_17 inner; int extra; };
struct Chain5_19 { Chain5_18 inner; int extra; };
struct Chain5_20 { Chain5_19 inner; int extra; };
static_assert(is_sendable_v<Chain5_20>);
struct Chain6_0 { int value; };
struct Chain6_1 { Chain6_0 inner; int extra; };
struct Chain6_2 { Chain6_1 inner; int extra; };
struct Chain6_3 { Chain6_2 inner; int extra; };
struct Chain6_4 { Chain6_3 inner; int extra; };
struct Chain6_5 { Chain6_4 inner; int extra; };
struct Chain6_6 { Chain6_5 inner; int extra; };
struct Chain6_7 { Chain6_6 inner; int extra; };
struct Chain6_8 { Chain6_7 inner; int extra; };
struct Chain6_9 { Chain6_8 inner; int extra; };
struct Chain6_10 { Chain6_9 inner; int extra; };
struct Chain6_11 { Chain6_10 inner; int extra; };
struct Chain6_12 { Chain6_11 inner; int extra; };
struct Chain6_13 { Chain6_12 inner; int extra; };
struct Chain6_14 { Chain6_13 inner; int extra; };
struct Chain6_15 { Chain6_14 inner; int extra; };
struct Chain6_16 { Chain6_15 inner; int extra; };
struct Chain6_17 { Chain6_16 inner; int extra; };
struct Chain6_18 { Chain6_17 inner; int extra; };
struct Chain6_19 { Chain6_18 inner; int extra; };
struct Chain6_20 { Chain6_19 inner; int extra; };
static_assert(is_sendable_v<Chain6_20>);
struct Chain7_0 { int value; };
struct Chain7_1 { Chain7_0 inner; int extra; };
struct Chain7_2 { Chain7_1 inner; int extra; };
struct Chain7_3 { Chain7_2 inner; int extra; };
struct Chain7_4 { Chain7_3 inner; int extra; };
struct Chain7_5 { Chain7_4 inner; int extra; };
struct Chain7_6 { Chain7_5 inner; int extra; };
struct Chain7_7 { Chain7_6 inner; int extra; };
struct Chain7_8 { Chain7_7 inner; int extra; };
struct Chain7_9 { Chain7_8 inner; int extra; };
struct Chain7_10 { Chain7_9 inner; int extra; };
struct Chain7_11 { Chain7_10 inner; int extra; };
struct Chain7_12 { Chain7_11 inner; int extra; };
struct Chain7_13 { Chain7_12 inner; int extra; };
struct Chain7_14 { Chain7_13 inner; int extra; };
struct Chain7_15 { Chain7_14 inner; int extra; };
struct Chain7_16 { Chain7_15 inner; int extra; };
struct Chain7_17 { Chain7_16 inner; int extra; };
struct Chain7_18 { Chain7_17 inner; int extra; };
struct Chain7_19 { Chain7_18 inner; int extra; };
struct Chain7_20 { Chain7_19 inner; int extra; };
static_assert(is_sendable_v<Chain7_20>);
struct Chain8_0 { int value; };
struct Chain8_1 { Chain8_0 inner; int extra; };
struct Chain8_2 { Chain8_1 inner; int extra; };
struct Chain8_3 { Chain8_2 inner; int extra; };
struct Chain8_4 { Chain8_3 inner; int extra; };
struct Chain8_5 { Chain8_4 inner; int extra; };
struct Chain8_6 { Chain8_5 inner; int extra; };
struct Chain8_7 { Chain8_6 inner; int extra; };
struct Chain8_8 { Chain8_7 inner; int extra; };
struct Chain8_9 { Chain8_8 inner; int extra; };
struct Chain8_10 { Chain8_9 inner; int extra; };
struct Chain8_11 { Chain8_10 inner; int extra; };
struct Chain8_12 { Chain8_11 inner; int extra; };
struct Chain8_13 { Chain8_12 inner; int extra; };
struct Chain8_14 { Chain8_13 inner; int extra; };
struct Chain8_15 { Chain8_14 inner; int extra; };
struct Chain8_16 { Chain8_15 inner; int extra; };
struct Chain8_17 { Chain8_16 inner; int extra; };
struct Chain8_18 { Chain8_17 inner; int extra; };
struct Chain8_19 { Chain8_18 inner; int extra; };
struct Chain8_20 { Chain8_19 inner; int extra; };
static_assert(is_sendable_v<Chain8_20>);
struct Chain9_0 { int value; };
struct Chain9_1 { Chain9_0 inner; int extra; };
struct Chain9_2 { Chain9_1 inner; int extra; };
struct Chain9_3 { Chain9_2 inner; int extra; };
struct Chain9_4 { Chain9_3 inner; int extra; };
struct Chain9_5 { Chain9_4 inner; int extra; };
struct Chain9_6 { Chain9_5 inner; int extra; };
struct Chain9_7 { Chain9_6 inner; int extra; };
struct Chain9_8 { Chain9_7 inner; int extra; };
struct Chain9_9 { Chain9_8 inner; int extra; };
struct Chain9_10 { Chain9_9 inner; int extra; };
struct Chain9_11 { Chain9_10 inner; int extra; };
struct Chain9_12 { Chain9_11 inner; int extra; };
struct Chain9_13 { Chain9_12 inner; int extra; };
struct Chain9_14 { Chain9_13 inner; int extra; };
struct Chain9_15 { Chain9_14 inner; int extra; };
struct Chain9_16 { Chain9_15 inner; int extra; };
struct Chain9_17 { Chain9_16 inner; int extra; };
struct Chain9_18 { Chain9_17 inner; int extra; };
struct Chain9_19 { Chain9_18 inner; int extra; };
struct Chain9_20 { Chain9_19 inner; int extra; };
static_assert(is_sendable_v<Chain9_20>);
int main(){}
