#include <threadsafe/threadsafe.h>
using threadsafe::is_sendable_v;
struct Bad0 { int *borrowed; };
static_assert(!is_sendable_v<Bad0>);
struct Bad1 { int *borrowed; };
static_assert(!is_sendable_v<Bad1>);
struct Bad2 { int *borrowed; };
static_assert(!is_sendable_v<Bad2>);
struct Bad3 { int *borrowed; };
static_assert(!is_sendable_v<Bad3>);
struct Bad4 { int *borrowed; };
static_assert(!is_sendable_v<Bad4>);
struct Bad5 { int *borrowed; };
static_assert(!is_sendable_v<Bad5>);
struct Bad6 { int *borrowed; };
static_assert(!is_sendable_v<Bad6>);
struct Bad7 { int *borrowed; };
static_assert(!is_sendable_v<Bad7>);
struct Bad8 { int *borrowed; };
static_assert(!is_sendable_v<Bad8>);
struct Bad9 { int *borrowed; };
static_assert(!is_sendable_v<Bad9>);
struct Bad10 { int *borrowed; };
static_assert(!is_sendable_v<Bad10>);
struct Bad11 { int *borrowed; };
static_assert(!is_sendable_v<Bad11>);
struct Bad12 { int *borrowed; };
static_assert(!is_sendable_v<Bad12>);
struct Bad13 { int *borrowed; };
static_assert(!is_sendable_v<Bad13>);
struct Bad14 { int *borrowed; };
static_assert(!is_sendable_v<Bad14>);
struct Bad15 { int *borrowed; };
static_assert(!is_sendable_v<Bad15>);
struct Bad16 { int *borrowed; };
static_assert(!is_sendable_v<Bad16>);
struct Bad17 { int *borrowed; };
static_assert(!is_sendable_v<Bad17>);
struct Bad18 { int *borrowed; };
static_assert(!is_sendable_v<Bad18>);
struct Bad19 { int *borrowed; };
static_assert(!is_sendable_v<Bad19>);
struct Bad20 { int *borrowed; };
static_assert(!is_sendable_v<Bad20>);
struct Bad21 { int *borrowed; };
static_assert(!is_sendable_v<Bad21>);
struct Bad22 { int *borrowed; };
static_assert(!is_sendable_v<Bad22>);
struct Bad23 { int *borrowed; };
static_assert(!is_sendable_v<Bad23>);
struct Bad24 { int *borrowed; };
static_assert(!is_sendable_v<Bad24>);
struct Bad25 { int *borrowed; };
static_assert(!is_sendable_v<Bad25>);
struct Bad26 { int *borrowed; };
static_assert(!is_sendable_v<Bad26>);
struct Bad27 { int *borrowed; };
static_assert(!is_sendable_v<Bad27>);
struct Bad28 { int *borrowed; };
static_assert(!is_sendable_v<Bad28>);
struct Bad29 { int *borrowed; };
static_assert(!is_sendable_v<Bad29>);
struct Bad30 { int *borrowed; };
static_assert(!is_sendable_v<Bad30>);
struct Bad31 { int *borrowed; };
static_assert(!is_sendable_v<Bad31>);
struct Bad32 { int *borrowed; };
static_assert(!is_sendable_v<Bad32>);
struct Bad33 { int *borrowed; };
static_assert(!is_sendable_v<Bad33>);
struct Bad34 { int *borrowed; };
static_assert(!is_sendable_v<Bad34>);
struct Bad35 { int *borrowed; };
static_assert(!is_sendable_v<Bad35>);
struct Bad36 { int *borrowed; };
static_assert(!is_sendable_v<Bad36>);
struct Bad37 { int *borrowed; };
static_assert(!is_sendable_v<Bad37>);
struct Bad38 { int *borrowed; };
static_assert(!is_sendable_v<Bad38>);
struct Bad39 { int *borrowed; };
static_assert(!is_sendable_v<Bad39>);
struct Bad40 { int *borrowed; };
static_assert(!is_sendable_v<Bad40>);
struct Bad41 { int *borrowed; };
static_assert(!is_sendable_v<Bad41>);
struct Bad42 { int *borrowed; };
static_assert(!is_sendable_v<Bad42>);
struct Bad43 { int *borrowed; };
static_assert(!is_sendable_v<Bad43>);
struct Bad44 { int *borrowed; };
static_assert(!is_sendable_v<Bad44>);
struct Bad45 { int *borrowed; };
static_assert(!is_sendable_v<Bad45>);
struct Bad46 { int *borrowed; };
static_assert(!is_sendable_v<Bad46>);
struct Bad47 { int *borrowed; };
static_assert(!is_sendable_v<Bad47>);
struct Bad48 { int *borrowed; };
static_assert(!is_sendable_v<Bad48>);
struct Bad49 { int *borrowed; };
static_assert(!is_sendable_v<Bad49>);
struct Bad50 { int *borrowed; };
static_assert(!is_sendable_v<Bad50>);
struct Bad51 { int *borrowed; };
static_assert(!is_sendable_v<Bad51>);
struct Bad52 { int *borrowed; };
static_assert(!is_sendable_v<Bad52>);
struct Bad53 { int *borrowed; };
static_assert(!is_sendable_v<Bad53>);
struct Bad54 { int *borrowed; };
static_assert(!is_sendable_v<Bad54>);
struct Bad55 { int *borrowed; };
static_assert(!is_sendable_v<Bad55>);
struct Bad56 { int *borrowed; };
static_assert(!is_sendable_v<Bad56>);
struct Bad57 { int *borrowed; };
static_assert(!is_sendable_v<Bad57>);
struct Bad58 { int *borrowed; };
static_assert(!is_sendable_v<Bad58>);
struct Bad59 { int *borrowed; };
static_assert(!is_sendable_v<Bad59>);
struct Bad60 { int *borrowed; };
static_assert(!is_sendable_v<Bad60>);
struct Bad61 { int *borrowed; };
static_assert(!is_sendable_v<Bad61>);
struct Bad62 { int *borrowed; };
static_assert(!is_sendable_v<Bad62>);
struct Bad63 { int *borrowed; };
static_assert(!is_sendable_v<Bad63>);
struct Bad64 { int *borrowed; };
static_assert(!is_sendable_v<Bad64>);
struct Bad65 { int *borrowed; };
static_assert(!is_sendable_v<Bad65>);
struct Bad66 { int *borrowed; };
static_assert(!is_sendable_v<Bad66>);
struct Bad67 { int *borrowed; };
static_assert(!is_sendable_v<Bad67>);
struct Bad68 { int *borrowed; };
static_assert(!is_sendable_v<Bad68>);
struct Bad69 { int *borrowed; };
static_assert(!is_sendable_v<Bad69>);
struct Bad70 { int *borrowed; };
static_assert(!is_sendable_v<Bad70>);
struct Bad71 { int *borrowed; };
static_assert(!is_sendable_v<Bad71>);
struct Bad72 { int *borrowed; };
static_assert(!is_sendable_v<Bad72>);
struct Bad73 { int *borrowed; };
static_assert(!is_sendable_v<Bad73>);
struct Bad74 { int *borrowed; };
static_assert(!is_sendable_v<Bad74>);
struct Bad75 { int *borrowed; };
static_assert(!is_sendable_v<Bad75>);
struct Bad76 { int *borrowed; };
static_assert(!is_sendable_v<Bad76>);
struct Bad77 { int *borrowed; };
static_assert(!is_sendable_v<Bad77>);
struct Bad78 { int *borrowed; };
static_assert(!is_sendable_v<Bad78>);
struct Bad79 { int *borrowed; };
static_assert(!is_sendable_v<Bad79>);
struct Bad80 { int *borrowed; };
static_assert(!is_sendable_v<Bad80>);
struct Bad81 { int *borrowed; };
static_assert(!is_sendable_v<Bad81>);
struct Bad82 { int *borrowed; };
static_assert(!is_sendable_v<Bad82>);
struct Bad83 { int *borrowed; };
static_assert(!is_sendable_v<Bad83>);
struct Bad84 { int *borrowed; };
static_assert(!is_sendable_v<Bad84>);
struct Bad85 { int *borrowed; };
static_assert(!is_sendable_v<Bad85>);
struct Bad86 { int *borrowed; };
static_assert(!is_sendable_v<Bad86>);
struct Bad87 { int *borrowed; };
static_assert(!is_sendable_v<Bad87>);
struct Bad88 { int *borrowed; };
static_assert(!is_sendable_v<Bad88>);
struct Bad89 { int *borrowed; };
static_assert(!is_sendable_v<Bad89>);
struct Bad90 { int *borrowed; };
static_assert(!is_sendable_v<Bad90>);
struct Bad91 { int *borrowed; };
static_assert(!is_sendable_v<Bad91>);
struct Bad92 { int *borrowed; };
static_assert(!is_sendable_v<Bad92>);
struct Bad93 { int *borrowed; };
static_assert(!is_sendable_v<Bad93>);
struct Bad94 { int *borrowed; };
static_assert(!is_sendable_v<Bad94>);
struct Bad95 { int *borrowed; };
static_assert(!is_sendable_v<Bad95>);
struct Bad96 { int *borrowed; };
static_assert(!is_sendable_v<Bad96>);
struct Bad97 { int *borrowed; };
static_assert(!is_sendable_v<Bad97>);
struct Bad98 { int *borrowed; };
static_assert(!is_sendable_v<Bad98>);
struct Bad99 { int *borrowed; };
static_assert(!is_sendable_v<Bad99>);
struct Bad100 { int *borrowed; };
static_assert(!is_sendable_v<Bad100>);
struct Bad101 { int *borrowed; };
static_assert(!is_sendable_v<Bad101>);
struct Bad102 { int *borrowed; };
static_assert(!is_sendable_v<Bad102>);
struct Bad103 { int *borrowed; };
static_assert(!is_sendable_v<Bad103>);
struct Bad104 { int *borrowed; };
static_assert(!is_sendable_v<Bad104>);
struct Bad105 { int *borrowed; };
static_assert(!is_sendable_v<Bad105>);
struct Bad106 { int *borrowed; };
static_assert(!is_sendable_v<Bad106>);
struct Bad107 { int *borrowed; };
static_assert(!is_sendable_v<Bad107>);
struct Bad108 { int *borrowed; };
static_assert(!is_sendable_v<Bad108>);
struct Bad109 { int *borrowed; };
static_assert(!is_sendable_v<Bad109>);
struct Bad110 { int *borrowed; };
static_assert(!is_sendable_v<Bad110>);
struct Bad111 { int *borrowed; };
static_assert(!is_sendable_v<Bad111>);
struct Bad112 { int *borrowed; };
static_assert(!is_sendable_v<Bad112>);
struct Bad113 { int *borrowed; };
static_assert(!is_sendable_v<Bad113>);
struct Bad114 { int *borrowed; };
static_assert(!is_sendable_v<Bad114>);
struct Bad115 { int *borrowed; };
static_assert(!is_sendable_v<Bad115>);
struct Bad116 { int *borrowed; };
static_assert(!is_sendable_v<Bad116>);
struct Bad117 { int *borrowed; };
static_assert(!is_sendable_v<Bad117>);
struct Bad118 { int *borrowed; };
static_assert(!is_sendable_v<Bad118>);
struct Bad119 { int *borrowed; };
static_assert(!is_sendable_v<Bad119>);
struct Bad120 { int *borrowed; };
static_assert(!is_sendable_v<Bad120>);
struct Bad121 { int *borrowed; };
static_assert(!is_sendable_v<Bad121>);
struct Bad122 { int *borrowed; };
static_assert(!is_sendable_v<Bad122>);
struct Bad123 { int *borrowed; };
static_assert(!is_sendable_v<Bad123>);
struct Bad124 { int *borrowed; };
static_assert(!is_sendable_v<Bad124>);
struct Bad125 { int *borrowed; };
static_assert(!is_sendable_v<Bad125>);
struct Bad126 { int *borrowed; };
static_assert(!is_sendable_v<Bad126>);
struct Bad127 { int *borrowed; };
static_assert(!is_sendable_v<Bad127>);
struct Bad128 { int *borrowed; };
static_assert(!is_sendable_v<Bad128>);
struct Bad129 { int *borrowed; };
static_assert(!is_sendable_v<Bad129>);
struct Bad130 { int *borrowed; };
static_assert(!is_sendable_v<Bad130>);
struct Bad131 { int *borrowed; };
static_assert(!is_sendable_v<Bad131>);
struct Bad132 { int *borrowed; };
static_assert(!is_sendable_v<Bad132>);
struct Bad133 { int *borrowed; };
static_assert(!is_sendable_v<Bad133>);
struct Bad134 { int *borrowed; };
static_assert(!is_sendable_v<Bad134>);
struct Bad135 { int *borrowed; };
static_assert(!is_sendable_v<Bad135>);
struct Bad136 { int *borrowed; };
static_assert(!is_sendable_v<Bad136>);
struct Bad137 { int *borrowed; };
static_assert(!is_sendable_v<Bad137>);
struct Bad138 { int *borrowed; };
static_assert(!is_sendable_v<Bad138>);
struct Bad139 { int *borrowed; };
static_assert(!is_sendable_v<Bad139>);
struct Bad140 { int *borrowed; };
static_assert(!is_sendable_v<Bad140>);
struct Bad141 { int *borrowed; };
static_assert(!is_sendable_v<Bad141>);
struct Bad142 { int *borrowed; };
static_assert(!is_sendable_v<Bad142>);
struct Bad143 { int *borrowed; };
static_assert(!is_sendable_v<Bad143>);
struct Bad144 { int *borrowed; };
static_assert(!is_sendable_v<Bad144>);
struct Bad145 { int *borrowed; };
static_assert(!is_sendable_v<Bad145>);
struct Bad146 { int *borrowed; };
static_assert(!is_sendable_v<Bad146>);
struct Bad147 { int *borrowed; };
static_assert(!is_sendable_v<Bad147>);
struct Bad148 { int *borrowed; };
static_assert(!is_sendable_v<Bad148>);
struct Bad149 { int *borrowed; };
static_assert(!is_sendable_v<Bad149>);
struct Bad150 { int *borrowed; };
static_assert(!is_sendable_v<Bad150>);
struct Bad151 { int *borrowed; };
static_assert(!is_sendable_v<Bad151>);
struct Bad152 { int *borrowed; };
static_assert(!is_sendable_v<Bad152>);
struct Bad153 { int *borrowed; };
static_assert(!is_sendable_v<Bad153>);
struct Bad154 { int *borrowed; };
static_assert(!is_sendable_v<Bad154>);
struct Bad155 { int *borrowed; };
static_assert(!is_sendable_v<Bad155>);
struct Bad156 { int *borrowed; };
static_assert(!is_sendable_v<Bad156>);
struct Bad157 { int *borrowed; };
static_assert(!is_sendable_v<Bad157>);
struct Bad158 { int *borrowed; };
static_assert(!is_sendable_v<Bad158>);
struct Bad159 { int *borrowed; };
static_assert(!is_sendable_v<Bad159>);
struct Bad160 { int *borrowed; };
static_assert(!is_sendable_v<Bad160>);
struct Bad161 { int *borrowed; };
static_assert(!is_sendable_v<Bad161>);
struct Bad162 { int *borrowed; };
static_assert(!is_sendable_v<Bad162>);
struct Bad163 { int *borrowed; };
static_assert(!is_sendable_v<Bad163>);
struct Bad164 { int *borrowed; };
static_assert(!is_sendable_v<Bad164>);
struct Bad165 { int *borrowed; };
static_assert(!is_sendable_v<Bad165>);
struct Bad166 { int *borrowed; };
static_assert(!is_sendable_v<Bad166>);
struct Bad167 { int *borrowed; };
static_assert(!is_sendable_v<Bad167>);
struct Bad168 { int *borrowed; };
static_assert(!is_sendable_v<Bad168>);
struct Bad169 { int *borrowed; };
static_assert(!is_sendable_v<Bad169>);
struct Bad170 { int *borrowed; };
static_assert(!is_sendable_v<Bad170>);
struct Bad171 { int *borrowed; };
static_assert(!is_sendable_v<Bad171>);
struct Bad172 { int *borrowed; };
static_assert(!is_sendable_v<Bad172>);
struct Bad173 { int *borrowed; };
static_assert(!is_sendable_v<Bad173>);
struct Bad174 { int *borrowed; };
static_assert(!is_sendable_v<Bad174>);
struct Bad175 { int *borrowed; };
static_assert(!is_sendable_v<Bad175>);
struct Bad176 { int *borrowed; };
static_assert(!is_sendable_v<Bad176>);
struct Bad177 { int *borrowed; };
static_assert(!is_sendable_v<Bad177>);
struct Bad178 { int *borrowed; };
static_assert(!is_sendable_v<Bad178>);
struct Bad179 { int *borrowed; };
static_assert(!is_sendable_v<Bad179>);
struct Bad180 { int *borrowed; };
static_assert(!is_sendable_v<Bad180>);
struct Bad181 { int *borrowed; };
static_assert(!is_sendable_v<Bad181>);
struct Bad182 { int *borrowed; };
static_assert(!is_sendable_v<Bad182>);
struct Bad183 { int *borrowed; };
static_assert(!is_sendable_v<Bad183>);
struct Bad184 { int *borrowed; };
static_assert(!is_sendable_v<Bad184>);
struct Bad185 { int *borrowed; };
static_assert(!is_sendable_v<Bad185>);
struct Bad186 { int *borrowed; };
static_assert(!is_sendable_v<Bad186>);
struct Bad187 { int *borrowed; };
static_assert(!is_sendable_v<Bad187>);
struct Bad188 { int *borrowed; };
static_assert(!is_sendable_v<Bad188>);
struct Bad189 { int *borrowed; };
static_assert(!is_sendable_v<Bad189>);
struct Bad190 { int *borrowed; };
static_assert(!is_sendable_v<Bad190>);
struct Bad191 { int *borrowed; };
static_assert(!is_sendable_v<Bad191>);
struct Bad192 { int *borrowed; };
static_assert(!is_sendable_v<Bad192>);
struct Bad193 { int *borrowed; };
static_assert(!is_sendable_v<Bad193>);
struct Bad194 { int *borrowed; };
static_assert(!is_sendable_v<Bad194>);
struct Bad195 { int *borrowed; };
static_assert(!is_sendable_v<Bad195>);
struct Bad196 { int *borrowed; };
static_assert(!is_sendable_v<Bad196>);
struct Bad197 { int *borrowed; };
static_assert(!is_sendable_v<Bad197>);
struct Bad198 { int *borrowed; };
static_assert(!is_sendable_v<Bad198>);
struct Bad199 { int *borrowed; };
static_assert(!is_sendable_v<Bad199>);
struct Bad200 { int *borrowed; };
static_assert(!is_sendable_v<Bad200>);
struct Bad201 { int *borrowed; };
static_assert(!is_sendable_v<Bad201>);
struct Bad202 { int *borrowed; };
static_assert(!is_sendable_v<Bad202>);
struct Bad203 { int *borrowed; };
static_assert(!is_sendable_v<Bad203>);
struct Bad204 { int *borrowed; };
static_assert(!is_sendable_v<Bad204>);
struct Bad205 { int *borrowed; };
static_assert(!is_sendable_v<Bad205>);
struct Bad206 { int *borrowed; };
static_assert(!is_sendable_v<Bad206>);
struct Bad207 { int *borrowed; };
static_assert(!is_sendable_v<Bad207>);
struct Bad208 { int *borrowed; };
static_assert(!is_sendable_v<Bad208>);
struct Bad209 { int *borrowed; };
static_assert(!is_sendable_v<Bad209>);
struct Bad210 { int *borrowed; };
static_assert(!is_sendable_v<Bad210>);
struct Bad211 { int *borrowed; };
static_assert(!is_sendable_v<Bad211>);
struct Bad212 { int *borrowed; };
static_assert(!is_sendable_v<Bad212>);
struct Bad213 { int *borrowed; };
static_assert(!is_sendable_v<Bad213>);
struct Bad214 { int *borrowed; };
static_assert(!is_sendable_v<Bad214>);
struct Bad215 { int *borrowed; };
static_assert(!is_sendable_v<Bad215>);
struct Bad216 { int *borrowed; };
static_assert(!is_sendable_v<Bad216>);
struct Bad217 { int *borrowed; };
static_assert(!is_sendable_v<Bad217>);
struct Bad218 { int *borrowed; };
static_assert(!is_sendable_v<Bad218>);
struct Bad219 { int *borrowed; };
static_assert(!is_sendable_v<Bad219>);
struct Bad220 { int *borrowed; };
static_assert(!is_sendable_v<Bad220>);
struct Bad221 { int *borrowed; };
static_assert(!is_sendable_v<Bad221>);
struct Bad222 { int *borrowed; };
static_assert(!is_sendable_v<Bad222>);
struct Bad223 { int *borrowed; };
static_assert(!is_sendable_v<Bad223>);
struct Bad224 { int *borrowed; };
static_assert(!is_sendable_v<Bad224>);
struct Bad225 { int *borrowed; };
static_assert(!is_sendable_v<Bad225>);
struct Bad226 { int *borrowed; };
static_assert(!is_sendable_v<Bad226>);
struct Bad227 { int *borrowed; };
static_assert(!is_sendable_v<Bad227>);
struct Bad228 { int *borrowed; };
static_assert(!is_sendable_v<Bad228>);
struct Bad229 { int *borrowed; };
static_assert(!is_sendable_v<Bad229>);
struct Bad230 { int *borrowed; };
static_assert(!is_sendable_v<Bad230>);
struct Bad231 { int *borrowed; };
static_assert(!is_sendable_v<Bad231>);
struct Bad232 { int *borrowed; };
static_assert(!is_sendable_v<Bad232>);
struct Bad233 { int *borrowed; };
static_assert(!is_sendable_v<Bad233>);
struct Bad234 { int *borrowed; };
static_assert(!is_sendable_v<Bad234>);
struct Bad235 { int *borrowed; };
static_assert(!is_sendable_v<Bad235>);
struct Bad236 { int *borrowed; };
static_assert(!is_sendable_v<Bad236>);
struct Bad237 { int *borrowed; };
static_assert(!is_sendable_v<Bad237>);
struct Bad238 { int *borrowed; };
static_assert(!is_sendable_v<Bad238>);
struct Bad239 { int *borrowed; };
static_assert(!is_sendable_v<Bad239>);
struct Bad240 { int *borrowed; };
static_assert(!is_sendable_v<Bad240>);
struct Bad241 { int *borrowed; };
static_assert(!is_sendable_v<Bad241>);
struct Bad242 { int *borrowed; };
static_assert(!is_sendable_v<Bad242>);
struct Bad243 { int *borrowed; };
static_assert(!is_sendable_v<Bad243>);
struct Bad244 { int *borrowed; };
static_assert(!is_sendable_v<Bad244>);
struct Bad245 { int *borrowed; };
static_assert(!is_sendable_v<Bad245>);
struct Bad246 { int *borrowed; };
static_assert(!is_sendable_v<Bad246>);
struct Bad247 { int *borrowed; };
static_assert(!is_sendable_v<Bad247>);
struct Bad248 { int *borrowed; };
static_assert(!is_sendable_v<Bad248>);
struct Bad249 { int *borrowed; };
static_assert(!is_sendable_v<Bad249>);
struct Bad250 { int *borrowed; };
static_assert(!is_sendable_v<Bad250>);
struct Bad251 { int *borrowed; };
static_assert(!is_sendable_v<Bad251>);
struct Bad252 { int *borrowed; };
static_assert(!is_sendable_v<Bad252>);
struct Bad253 { int *borrowed; };
static_assert(!is_sendable_v<Bad253>);
struct Bad254 { int *borrowed; };
static_assert(!is_sendable_v<Bad254>);
struct Bad255 { int *borrowed; };
static_assert(!is_sendable_v<Bad255>);
struct Bad256 { int *borrowed; };
static_assert(!is_sendable_v<Bad256>);
struct Bad257 { int *borrowed; };
static_assert(!is_sendable_v<Bad257>);
struct Bad258 { int *borrowed; };
static_assert(!is_sendable_v<Bad258>);
struct Bad259 { int *borrowed; };
static_assert(!is_sendable_v<Bad259>);
struct Bad260 { int *borrowed; };
static_assert(!is_sendable_v<Bad260>);
struct Bad261 { int *borrowed; };
static_assert(!is_sendable_v<Bad261>);
struct Bad262 { int *borrowed; };
static_assert(!is_sendable_v<Bad262>);
struct Bad263 { int *borrowed; };
static_assert(!is_sendable_v<Bad263>);
struct Bad264 { int *borrowed; };
static_assert(!is_sendable_v<Bad264>);
struct Bad265 { int *borrowed; };
static_assert(!is_sendable_v<Bad265>);
struct Bad266 { int *borrowed; };
static_assert(!is_sendable_v<Bad266>);
struct Bad267 { int *borrowed; };
static_assert(!is_sendable_v<Bad267>);
struct Bad268 { int *borrowed; };
static_assert(!is_sendable_v<Bad268>);
struct Bad269 { int *borrowed; };
static_assert(!is_sendable_v<Bad269>);
struct Bad270 { int *borrowed; };
static_assert(!is_sendable_v<Bad270>);
struct Bad271 { int *borrowed; };
static_assert(!is_sendable_v<Bad271>);
struct Bad272 { int *borrowed; };
static_assert(!is_sendable_v<Bad272>);
struct Bad273 { int *borrowed; };
static_assert(!is_sendable_v<Bad273>);
struct Bad274 { int *borrowed; };
static_assert(!is_sendable_v<Bad274>);
struct Bad275 { int *borrowed; };
static_assert(!is_sendable_v<Bad275>);
struct Bad276 { int *borrowed; };
static_assert(!is_sendable_v<Bad276>);
struct Bad277 { int *borrowed; };
static_assert(!is_sendable_v<Bad277>);
struct Bad278 { int *borrowed; };
static_assert(!is_sendable_v<Bad278>);
struct Bad279 { int *borrowed; };
static_assert(!is_sendable_v<Bad279>);
struct Bad280 { int *borrowed; };
static_assert(!is_sendable_v<Bad280>);
struct Bad281 { int *borrowed; };
static_assert(!is_sendable_v<Bad281>);
struct Bad282 { int *borrowed; };
static_assert(!is_sendable_v<Bad282>);
struct Bad283 { int *borrowed; };
static_assert(!is_sendable_v<Bad283>);
struct Bad284 { int *borrowed; };
static_assert(!is_sendable_v<Bad284>);
struct Bad285 { int *borrowed; };
static_assert(!is_sendable_v<Bad285>);
struct Bad286 { int *borrowed; };
static_assert(!is_sendable_v<Bad286>);
struct Bad287 { int *borrowed; };
static_assert(!is_sendable_v<Bad287>);
struct Bad288 { int *borrowed; };
static_assert(!is_sendable_v<Bad288>);
struct Bad289 { int *borrowed; };
static_assert(!is_sendable_v<Bad289>);
struct Bad290 { int *borrowed; };
static_assert(!is_sendable_v<Bad290>);
struct Bad291 { int *borrowed; };
static_assert(!is_sendable_v<Bad291>);
struct Bad292 { int *borrowed; };
static_assert(!is_sendable_v<Bad292>);
struct Bad293 { int *borrowed; };
static_assert(!is_sendable_v<Bad293>);
struct Bad294 { int *borrowed; };
static_assert(!is_sendable_v<Bad294>);
struct Bad295 { int *borrowed; };
static_assert(!is_sendable_v<Bad295>);
struct Bad296 { int *borrowed; };
static_assert(!is_sendable_v<Bad296>);
struct Bad297 { int *borrowed; };
static_assert(!is_sendable_v<Bad297>);
struct Bad298 { int *borrowed; };
static_assert(!is_sendable_v<Bad298>);
struct Bad299 { int *borrowed; };
static_assert(!is_sendable_v<Bad299>);
struct Bad300 { int *borrowed; };
static_assert(!is_sendable_v<Bad300>);
struct Bad301 { int *borrowed; };
static_assert(!is_sendable_v<Bad301>);
struct Bad302 { int *borrowed; };
static_assert(!is_sendable_v<Bad302>);
struct Bad303 { int *borrowed; };
static_assert(!is_sendable_v<Bad303>);
struct Bad304 { int *borrowed; };
static_assert(!is_sendable_v<Bad304>);
struct Bad305 { int *borrowed; };
static_assert(!is_sendable_v<Bad305>);
struct Bad306 { int *borrowed; };
static_assert(!is_sendable_v<Bad306>);
struct Bad307 { int *borrowed; };
static_assert(!is_sendable_v<Bad307>);
struct Bad308 { int *borrowed; };
static_assert(!is_sendable_v<Bad308>);
struct Bad309 { int *borrowed; };
static_assert(!is_sendable_v<Bad309>);
struct Bad310 { int *borrowed; };
static_assert(!is_sendable_v<Bad310>);
struct Bad311 { int *borrowed; };
static_assert(!is_sendable_v<Bad311>);
struct Bad312 { int *borrowed; };
static_assert(!is_sendable_v<Bad312>);
struct Bad313 { int *borrowed; };
static_assert(!is_sendable_v<Bad313>);
struct Bad314 { int *borrowed; };
static_assert(!is_sendable_v<Bad314>);
struct Bad315 { int *borrowed; };
static_assert(!is_sendable_v<Bad315>);
struct Bad316 { int *borrowed; };
static_assert(!is_sendable_v<Bad316>);
struct Bad317 { int *borrowed; };
static_assert(!is_sendable_v<Bad317>);
struct Bad318 { int *borrowed; };
static_assert(!is_sendable_v<Bad318>);
struct Bad319 { int *borrowed; };
static_assert(!is_sendable_v<Bad319>);
struct Bad320 { int *borrowed; };
static_assert(!is_sendable_v<Bad320>);
struct Bad321 { int *borrowed; };
static_assert(!is_sendable_v<Bad321>);
struct Bad322 { int *borrowed; };
static_assert(!is_sendable_v<Bad322>);
struct Bad323 { int *borrowed; };
static_assert(!is_sendable_v<Bad323>);
struct Bad324 { int *borrowed; };
static_assert(!is_sendable_v<Bad324>);
struct Bad325 { int *borrowed; };
static_assert(!is_sendable_v<Bad325>);
struct Bad326 { int *borrowed; };
static_assert(!is_sendable_v<Bad326>);
struct Bad327 { int *borrowed; };
static_assert(!is_sendable_v<Bad327>);
struct Bad328 { int *borrowed; };
static_assert(!is_sendable_v<Bad328>);
struct Bad329 { int *borrowed; };
static_assert(!is_sendable_v<Bad329>);
struct Bad330 { int *borrowed; };
static_assert(!is_sendable_v<Bad330>);
struct Bad331 { int *borrowed; };
static_assert(!is_sendable_v<Bad331>);
struct Bad332 { int *borrowed; };
static_assert(!is_sendable_v<Bad332>);
struct Bad333 { int *borrowed; };
static_assert(!is_sendable_v<Bad333>);
struct Bad334 { int *borrowed; };
static_assert(!is_sendable_v<Bad334>);
struct Bad335 { int *borrowed; };
static_assert(!is_sendable_v<Bad335>);
struct Bad336 { int *borrowed; };
static_assert(!is_sendable_v<Bad336>);
struct Bad337 { int *borrowed; };
static_assert(!is_sendable_v<Bad337>);
struct Bad338 { int *borrowed; };
static_assert(!is_sendable_v<Bad338>);
struct Bad339 { int *borrowed; };
static_assert(!is_sendable_v<Bad339>);
struct Bad340 { int *borrowed; };
static_assert(!is_sendable_v<Bad340>);
struct Bad341 { int *borrowed; };
static_assert(!is_sendable_v<Bad341>);
struct Bad342 { int *borrowed; };
static_assert(!is_sendable_v<Bad342>);
struct Bad343 { int *borrowed; };
static_assert(!is_sendable_v<Bad343>);
struct Bad344 { int *borrowed; };
static_assert(!is_sendable_v<Bad344>);
struct Bad345 { int *borrowed; };
static_assert(!is_sendable_v<Bad345>);
struct Bad346 { int *borrowed; };
static_assert(!is_sendable_v<Bad346>);
struct Bad347 { int *borrowed; };
static_assert(!is_sendable_v<Bad347>);
struct Bad348 { int *borrowed; };
static_assert(!is_sendable_v<Bad348>);
struct Bad349 { int *borrowed; };
static_assert(!is_sendable_v<Bad349>);
struct Bad350 { int *borrowed; };
static_assert(!is_sendable_v<Bad350>);
struct Bad351 { int *borrowed; };
static_assert(!is_sendable_v<Bad351>);
struct Bad352 { int *borrowed; };
static_assert(!is_sendable_v<Bad352>);
struct Bad353 { int *borrowed; };
static_assert(!is_sendable_v<Bad353>);
struct Bad354 { int *borrowed; };
static_assert(!is_sendable_v<Bad354>);
struct Bad355 { int *borrowed; };
static_assert(!is_sendable_v<Bad355>);
struct Bad356 { int *borrowed; };
static_assert(!is_sendable_v<Bad356>);
struct Bad357 { int *borrowed; };
static_assert(!is_sendable_v<Bad357>);
struct Bad358 { int *borrowed; };
static_assert(!is_sendable_v<Bad358>);
struct Bad359 { int *borrowed; };
static_assert(!is_sendable_v<Bad359>);
struct Bad360 { int *borrowed; };
static_assert(!is_sendable_v<Bad360>);
struct Bad361 { int *borrowed; };
static_assert(!is_sendable_v<Bad361>);
struct Bad362 { int *borrowed; };
static_assert(!is_sendable_v<Bad362>);
struct Bad363 { int *borrowed; };
static_assert(!is_sendable_v<Bad363>);
struct Bad364 { int *borrowed; };
static_assert(!is_sendable_v<Bad364>);
struct Bad365 { int *borrowed; };
static_assert(!is_sendable_v<Bad365>);
struct Bad366 { int *borrowed; };
static_assert(!is_sendable_v<Bad366>);
struct Bad367 { int *borrowed; };
static_assert(!is_sendable_v<Bad367>);
struct Bad368 { int *borrowed; };
static_assert(!is_sendable_v<Bad368>);
struct Bad369 { int *borrowed; };
static_assert(!is_sendable_v<Bad369>);
struct Bad370 { int *borrowed; };
static_assert(!is_sendable_v<Bad370>);
struct Bad371 { int *borrowed; };
static_assert(!is_sendable_v<Bad371>);
struct Bad372 { int *borrowed; };
static_assert(!is_sendable_v<Bad372>);
struct Bad373 { int *borrowed; };
static_assert(!is_sendable_v<Bad373>);
struct Bad374 { int *borrowed; };
static_assert(!is_sendable_v<Bad374>);
struct Bad375 { int *borrowed; };
static_assert(!is_sendable_v<Bad375>);
struct Bad376 { int *borrowed; };
static_assert(!is_sendable_v<Bad376>);
struct Bad377 { int *borrowed; };
static_assert(!is_sendable_v<Bad377>);
struct Bad378 { int *borrowed; };
static_assert(!is_sendable_v<Bad378>);
struct Bad379 { int *borrowed; };
static_assert(!is_sendable_v<Bad379>);
struct Bad380 { int *borrowed; };
static_assert(!is_sendable_v<Bad380>);
struct Bad381 { int *borrowed; };
static_assert(!is_sendable_v<Bad381>);
struct Bad382 { int *borrowed; };
static_assert(!is_sendable_v<Bad382>);
struct Bad383 { int *borrowed; };
static_assert(!is_sendable_v<Bad383>);
struct Bad384 { int *borrowed; };
static_assert(!is_sendable_v<Bad384>);
struct Bad385 { int *borrowed; };
static_assert(!is_sendable_v<Bad385>);
struct Bad386 { int *borrowed; };
static_assert(!is_sendable_v<Bad386>);
struct Bad387 { int *borrowed; };
static_assert(!is_sendable_v<Bad387>);
struct Bad388 { int *borrowed; };
static_assert(!is_sendable_v<Bad388>);
struct Bad389 { int *borrowed; };
static_assert(!is_sendable_v<Bad389>);
struct Bad390 { int *borrowed; };
static_assert(!is_sendable_v<Bad390>);
struct Bad391 { int *borrowed; };
static_assert(!is_sendable_v<Bad391>);
struct Bad392 { int *borrowed; };
static_assert(!is_sendable_v<Bad392>);
struct Bad393 { int *borrowed; };
static_assert(!is_sendable_v<Bad393>);
struct Bad394 { int *borrowed; };
static_assert(!is_sendable_v<Bad394>);
struct Bad395 { int *borrowed; };
static_assert(!is_sendable_v<Bad395>);
struct Bad396 { int *borrowed; };
static_assert(!is_sendable_v<Bad396>);
struct Bad397 { int *borrowed; };
static_assert(!is_sendable_v<Bad397>);
struct Bad398 { int *borrowed; };
static_assert(!is_sendable_v<Bad398>);
struct Bad399 { int *borrowed; };
static_assert(!is_sendable_v<Bad399>);
