#include <threadsafe/threadsafe.h>
using namespace threadsafe;
struct Level0 { int value; };
struct Level1 { Level0 inner; };
struct Level2 { Level1 inner; };
struct Level3 { Level2 inner; };
struct Level4 { Level3 inner; };
struct Level5 { Level4 inner; };
struct Level6 { Level5 inner; };
struct Level7 { Level6 inner; };
struct Level8 { Level7 inner; };
struct Level9 { Level8 inner; };
struct Level10 { Level9 inner; };
struct Level11 { Level10 inner; };
struct Level12 { Level11 inner; };
struct Level13 { Level12 inner; };
struct Level14 { Level13 inner; };
struct Level15 { Level14 inner; };
struct Level16 { Level15 inner; };
struct Level17 { Level16 inner; };
struct Level18 { Level17 inner; };
struct Level19 { Level18 inner; };
struct Level20 { Level19 inner; };
struct Level21 { Level20 inner; };
struct Level22 { Level21 inner; };
struct Level23 { Level22 inner; };
struct Level24 { Level23 inner; };
struct Level25 { Level24 inner; };
struct Level26 { Level25 inner; };
struct Level27 { Level26 inner; };
struct Level28 { Level27 inner; };
struct Level29 { Level28 inner; };
struct Level30 { Level29 inner; };
struct Level31 { Level30 inner; };
struct Level32 { Level31 inner; };
struct Level33 { Level32 inner; };
struct Level34 { Level33 inner; };
struct Level35 { Level34 inner; };
struct Level36 { Level35 inner; };
struct Level37 { Level36 inner; };
struct Level38 { Level37 inner; };
struct Level39 { Level38 inner; };
struct Level40 { Level39 inner; };
static_assert(is_sendable_v<Level40>);
static_assert(is_synchronizable_v<const Level40>);
static_assert(is_lifetime_aware_v<Level40>);
