#include <threadsafe/threadsafe.h>
using threadsafe::is_sendable_v;
struct Ok0 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok0>);
struct Ok1 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok1>);
struct Ok2 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok2>);
struct Ok3 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok3>);
struct Ok4 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok4>);
struct Ok5 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok5>);
struct Ok6 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok6>);
struct Ok7 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok7>);
struct Ok8 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok8>);
struct Ok9 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok9>);
struct Ok10 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok10>);
struct Ok11 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok11>);
struct Ok12 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok12>);
struct Ok13 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok13>);
struct Ok14 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok14>);
struct Ok15 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok15>);
struct Ok16 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok16>);
struct Ok17 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok17>);
struct Ok18 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok18>);
struct Ok19 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok19>);
struct Ok20 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok20>);
struct Ok21 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok21>);
struct Ok22 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok22>);
struct Ok23 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok23>);
struct Ok24 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok24>);
struct Ok25 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok25>);
struct Ok26 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok26>);
struct Ok27 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok27>);
struct Ok28 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok28>);
struct Ok29 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok29>);
struct Ok30 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok30>);
struct Ok31 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok31>);
struct Ok32 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok32>);
struct Ok33 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok33>);
struct Ok34 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok34>);
struct Ok35 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok35>);
struct Ok36 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok36>);
struct Ok37 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok37>);
struct Ok38 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok38>);
struct Ok39 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok39>);
struct Ok40 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok40>);
struct Ok41 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok41>);
struct Ok42 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok42>);
struct Ok43 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok43>);
struct Ok44 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok44>);
struct Ok45 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok45>);
struct Ok46 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok46>);
struct Ok47 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok47>);
struct Ok48 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok48>);
struct Ok49 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok49>);
struct Ok50 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok50>);
struct Ok51 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok51>);
struct Ok52 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok52>);
struct Ok53 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok53>);
struct Ok54 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok54>);
struct Ok55 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok55>);
struct Ok56 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok56>);
struct Ok57 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok57>);
struct Ok58 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok58>);
struct Ok59 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok59>);
struct Ok60 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok60>);
struct Ok61 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok61>);
struct Ok62 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok62>);
struct Ok63 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok63>);
struct Ok64 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok64>);
struct Ok65 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok65>);
struct Ok66 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok66>);
struct Ok67 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok67>);
struct Ok68 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok68>);
struct Ok69 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok69>);
struct Ok70 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok70>);
struct Ok71 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok71>);
struct Ok72 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok72>);
struct Ok73 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok73>);
struct Ok74 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok74>);
struct Ok75 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok75>);
struct Ok76 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok76>);
struct Ok77 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok77>);
struct Ok78 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok78>);
struct Ok79 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok79>);
struct Ok80 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok80>);
struct Ok81 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok81>);
struct Ok82 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok82>);
struct Ok83 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok83>);
struct Ok84 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok84>);
struct Ok85 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok85>);
struct Ok86 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok86>);
struct Ok87 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok87>);
struct Ok88 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok88>);
struct Ok89 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok89>);
struct Ok90 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok90>);
struct Ok91 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok91>);
struct Ok92 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok92>);
struct Ok93 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok93>);
struct Ok94 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok94>);
struct Ok95 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok95>);
struct Ok96 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok96>);
struct Ok97 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok97>);
struct Ok98 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok98>);
struct Ok99 {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
};
static_assert(is_sendable_v<Ok99>);
