#include <threadsafe/threadsafe.h>
using namespace threadsafe;
struct Flat {
    int member_0;
    int member_1;
    int member_2;
    int member_3;
    int member_4;
    int member_5;
    int member_6;
    int member_7;
    int member_8;
    int member_9;
    int member_10;
    int member_11;
    int member_12;
    int member_13;
    int member_14;
    int member_15;
    int member_16;
    int member_17;
    int member_18;
    int member_19;
    int member_20;
    int member_21;
    int member_22;
    int member_23;
    int member_24;
    int member_25;
    int member_26;
    int member_27;
    int member_28;
    int member_29;
    int member_30;
    int member_31;
    int member_32;
    int member_33;
    int member_34;
    int member_35;
    int member_36;
    int member_37;
    int member_38;
    int member_39;
    int member_40;
    int member_41;
    int member_42;
    int member_43;
    int member_44;
    int member_45;
    int member_46;
    int member_47;
    int member_48;
    int member_49;
};
static_assert(is_sendable_v<Flat>);
static_assert(is_synchronizable_v<const Flat>);
static_assert(is_lifetime_aware_v<Flat>);
