#include <threadsafe/threadsafe.h>
struct Leaf { int *borrowed; };
struct A0 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A0>);
struct A1 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A1>);
struct A2 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A2>);
struct A3 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A3>);
struct A4 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A4>);
struct A5 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A5>);
struct A6 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A6>);
struct A7 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A7>);
struct A8 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A8>);
struct A9 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A9>);
struct A10 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A10>);
struct A11 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A11>);
struct A12 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A12>);
struct A13 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A13>);
struct A14 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A14>);
struct A15 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A15>);
struct A16 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A16>);
struct A17 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A17>);
struct A18 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A18>);
struct A19 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A19>);
struct A20 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A20>);
struct A21 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A21>);
struct A22 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A22>);
struct A23 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A23>);
struct A24 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A24>);
struct A25 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A25>);
struct A26 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A26>);
struct A27 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A27>);
struct A28 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A28>);
struct A29 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A29>);
struct A30 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A30>);
struct A31 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A31>);
struct A32 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A32>);
struct A33 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A33>);
struct A34 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A34>);
struct A35 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A35>);
struct A36 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A36>);
struct A37 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A37>);
struct A38 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A38>);
struct A39 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A39>);
struct A40 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A40>);
struct A41 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A41>);
struct A42 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A42>);
struct A43 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A43>);
struct A44 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A44>);
struct A45 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A45>);
struct A46 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A46>);
struct A47 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A47>);
struct A48 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A48>);
struct A49 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A49>);
struct A50 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A50>);
struct A51 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A51>);
struct A52 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A52>);
struct A53 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A53>);
struct A54 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A54>);
struct A55 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A55>);
struct A56 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A56>);
struct A57 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A57>);
struct A58 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A58>);
struct A59 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A59>);
struct A60 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A60>);
struct A61 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A61>);
struct A62 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A62>);
struct A63 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A63>);
struct A64 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A64>);
struct A65 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A65>);
struct A66 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A66>);
struct A67 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A67>);
struct A68 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A68>);
struct A69 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A69>);
struct A70 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A70>);
struct A71 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A71>);
struct A72 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A72>);
struct A73 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A73>);
struct A74 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A74>);
struct A75 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A75>);
struct A76 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A76>);
struct A77 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A77>);
struct A78 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A78>);
struct A79 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A79>);
struct A80 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A80>);
struct A81 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A81>);
struct A82 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A82>);
struct A83 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A83>);
struct A84 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A84>);
struct A85 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A85>);
struct A86 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A86>);
struct A87 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A87>);
struct A88 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A88>);
struct A89 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A89>);
struct A90 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A90>);
struct A91 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A91>);
struct A92 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A92>);
struct A93 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A93>);
struct A94 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A94>);
struct A95 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A95>);
struct A96 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A96>);
struct A97 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A97>);
struct A98 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A98>);
struct A99 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A99>);
struct A100 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A100>);
struct A101 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A101>);
struct A102 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A102>);
struct A103 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A103>);
struct A104 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A104>);
struct A105 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A105>);
struct A106 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A106>);
struct A107 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A107>);
struct A108 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A108>);
struct A109 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A109>);
struct A110 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A110>);
struct A111 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A111>);
struct A112 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A112>);
struct A113 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A113>);
struct A114 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A114>);
struct A115 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A115>);
struct A116 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A116>);
struct A117 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A117>);
struct A118 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A118>);
struct A119 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A119>);
struct A120 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A120>);
struct A121 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A121>);
struct A122 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A122>);
struct A123 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A123>);
struct A124 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A124>);
struct A125 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A125>);
struct A126 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A126>);
struct A127 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A127>);
struct A128 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A128>);
struct A129 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A129>);
struct A130 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A130>);
struct A131 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A131>);
struct A132 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A132>);
struct A133 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A133>);
struct A134 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A134>);
struct A135 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A135>);
struct A136 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A136>);
struct A137 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A137>);
struct A138 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A138>);
struct A139 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A139>);
struct A140 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A140>);
struct A141 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A141>);
struct A142 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A142>);
struct A143 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A143>);
struct A144 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A144>);
struct A145 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A145>);
struct A146 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A146>);
struct A147 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A147>);
struct A148 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A148>);
struct A149 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A149>);
struct A150 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A150>);
struct A151 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A151>);
struct A152 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A152>);
struct A153 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A153>);
struct A154 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A154>);
struct A155 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A155>);
struct A156 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A156>);
struct A157 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A157>);
struct A158 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A158>);
struct A159 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A159>);
struct A160 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A160>);
struct A161 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A161>);
struct A162 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A162>);
struct A163 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A163>);
struct A164 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A164>);
struct A165 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A165>);
struct A166 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A166>);
struct A167 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A167>);
struct A168 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A168>);
struct A169 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A169>);
struct A170 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A170>);
struct A171 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A171>);
struct A172 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A172>);
struct A173 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A173>);
struct A174 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A174>);
struct A175 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A175>);
struct A176 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A176>);
struct A177 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A177>);
struct A178 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A178>);
struct A179 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A179>);
struct A180 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A180>);
struct A181 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A181>);
struct A182 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A182>);
struct A183 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A183>);
struct A184 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A184>);
struct A185 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A185>);
struct A186 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A186>);
struct A187 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A187>);
struct A188 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A188>);
struct A189 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A189>);
struct A190 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A190>);
struct A191 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A191>);
struct A192 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A192>);
struct A193 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A193>);
struct A194 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A194>);
struct A195 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A195>);
struct A196 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A196>);
struct A197 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A197>);
struct A198 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A198>);
struct A199 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A199>);
struct A200 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A200>);
struct A201 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A201>);
struct A202 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A202>);
struct A203 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A203>);
struct A204 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A204>);
struct A205 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A205>);
struct A206 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A206>);
struct A207 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A207>);
struct A208 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A208>);
struct A209 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A209>);
struct A210 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A210>);
struct A211 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A211>);
struct A212 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A212>);
struct A213 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A213>);
struct A214 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A214>);
struct A215 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A215>);
struct A216 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A216>);
struct A217 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A217>);
struct A218 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A218>);
struct A219 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A219>);
struct A220 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A220>);
struct A221 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A221>);
struct A222 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A222>);
struct A223 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A223>);
struct A224 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A224>);
struct A225 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A225>);
struct A226 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A226>);
struct A227 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A227>);
struct A228 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A228>);
struct A229 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A229>);
struct A230 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A230>);
struct A231 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A231>);
struct A232 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A232>);
struct A233 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A233>);
struct A234 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A234>);
struct A235 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A235>);
struct A236 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A236>);
struct A237 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A237>);
struct A238 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A238>);
struct A239 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A239>);
struct A240 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A240>);
struct A241 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A241>);
struct A242 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A242>);
struct A243 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A243>);
struct A244 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A244>);
struct A245 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A245>);
struct A246 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A246>);
struct A247 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A247>);
struct A248 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A248>);
struct A249 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A249>);
struct A250 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A250>);
struct A251 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A251>);
struct A252 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A252>);
struct A253 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A253>);
struct A254 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A254>);
struct A255 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A255>);
struct A256 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A256>);
struct A257 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A257>);
struct A258 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A258>);
struct A259 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A259>);
struct A260 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A260>);
struct A261 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A261>);
struct A262 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A262>);
struct A263 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A263>);
struct A264 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A264>);
struct A265 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A265>);
struct A266 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A266>);
struct A267 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A267>);
struct A268 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A268>);
struct A269 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A269>);
struct A270 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A270>);
struct A271 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A271>);
struct A272 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A272>);
struct A273 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A273>);
struct A274 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A274>);
struct A275 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A275>);
struct A276 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A276>);
struct A277 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A277>);
struct A278 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A278>);
struct A279 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A279>);
struct A280 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A280>);
struct A281 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A281>);
struct A282 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A282>);
struct A283 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A283>);
struct A284 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A284>);
struct A285 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A285>);
struct A286 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A286>);
struct A287 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A287>);
struct A288 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A288>);
struct A289 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A289>);
struct A290 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A290>);
struct A291 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A291>);
struct A292 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A292>);
struct A293 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A293>);
struct A294 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A294>);
struct A295 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A295>);
struct A296 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A296>);
struct A297 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A297>);
struct A298 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A298>);
struct A299 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A299>);
struct A300 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A300>);
struct A301 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A301>);
struct A302 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A302>);
struct A303 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A303>);
struct A304 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A304>);
struct A305 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A305>);
struct A306 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A306>);
struct A307 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A307>);
struct A308 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A308>);
struct A309 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A309>);
struct A310 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A310>);
struct A311 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A311>);
struct A312 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A312>);
struct A313 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A313>);
struct A314 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A314>);
struct A315 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A315>);
struct A316 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A316>);
struct A317 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A317>);
struct A318 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A318>);
struct A319 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A319>);
struct A320 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A320>);
struct A321 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A321>);
struct A322 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A322>);
struct A323 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A323>);
struct A324 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A324>);
struct A325 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A325>);
struct A326 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A326>);
struct A327 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A327>);
struct A328 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A328>);
struct A329 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A329>);
struct A330 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A330>);
struct A331 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A331>);
struct A332 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A332>);
struct A333 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A333>);
struct A334 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A334>);
struct A335 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A335>);
struct A336 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A336>);
struct A337 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A337>);
struct A338 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A338>);
struct A339 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A339>);
struct A340 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A340>);
struct A341 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A341>);
struct A342 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A342>);
struct A343 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A343>);
struct A344 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A344>);
struct A345 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A345>);
struct A346 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A346>);
struct A347 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A347>);
struct A348 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A348>);
struct A349 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A349>);
struct A350 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A350>);
struct A351 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A351>);
struct A352 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A352>);
struct A353 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A353>);
struct A354 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A354>);
struct A355 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A355>);
struct A356 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A356>);
struct A357 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A357>);
struct A358 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A358>);
struct A359 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A359>);
struct A360 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A360>);
struct A361 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A361>);
struct A362 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A362>);
struct A363 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A363>);
struct A364 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A364>);
struct A365 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A365>);
struct A366 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A366>);
struct A367 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A367>);
struct A368 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A368>);
struct A369 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A369>);
struct A370 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A370>);
struct A371 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A371>);
struct A372 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A372>);
struct A373 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A373>);
struct A374 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A374>);
struct A375 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A375>);
struct A376 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A376>);
struct A377 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A377>);
struct A378 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A378>);
struct A379 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A379>);
struct A380 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A380>);
struct A381 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A381>);
struct A382 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A382>);
struct A383 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A383>);
struct A384 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A384>);
struct A385 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A385>);
struct A386 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A386>);
struct A387 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A387>);
struct A388 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A388>);
struct A389 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A389>);
struct A390 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A390>);
struct A391 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A391>);
struct A392 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A392>);
struct A393 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A393>);
struct A394 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A394>);
struct A395 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A395>);
struct A396 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A396>);
struct A397 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A397>);
struct A398 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A398>);
struct A399 { Leaf a; int b; double c; };
static_assert(!threadsafe::is_sendable_v<A399>);
